### ISSUE TITLE
diff detected issues against older commits to detect new issues

### ISSUE THREAD

**Issue by guykisel** [guykisel/inline-plz#30]
sometimes there are new problems in code that's outside the direct diff, but are a result of the new changes. we could diff the reported lint issues against lint issues from older commits to detect these new problems.

**Comment by raphaelcastaneda** [comment]
It would be nice to see an interface-agnostic way of doing this. However, as of right now the logic for whether a lint message gets posted as a comment is tied to the implementation of `GithubInterface`

**Comment by guykisel** [comment]
fixed in #324
