### ISSUE TITLE
Possible jshint bug, not commenting missing semicolon

### ISSUE THREAD

**Issue by midniteio** [guykisel/inline-plz#54]
Ran into this- locally I have missing semicolon issue:

λ npm test
> jshint . && jscs .

commands.js: line 295, col 87, Missing semicolon.
commands.js: line 554, col 2, Missing semicolon.

2 errors
npm ERR! Test failed.  See above for more details.

**Comment by guykisel** [comment]
fixed in https://github.com/guykisel/inline-plz/commit/39232c5d4cc35e3bf2dca548b1111043feb1df1f (which i accidentally pushed directly to master because i'm bad at git)
